### ISSUE TITLE
级还是届？

### ISSUE THREAD

**Issue by Yuchen-Wang-SH** [ECUST-Leap/ecust-leap.github.io#113]
我们现在用的是级，即入学年份。

我提议我们用届，即毕业年份，这样的话数字更贴近当前年份，想的时候不用脑海中加4年去想这个人出国/找工作/保研/考研这件事情是发生在几几年的

**Comment by Oliver20001031** [comment]
这个我觉得统一标准就好，我们学校好像没有特殊的学制的

**Comment by Yuchen-Wang-SH** [comment]
@ECUST-Leap/f23-editors 大家怎么看

**Comment by Yuchen-Wang-SH** [comment]
我又转念一想 在学校的时候都是以入学年份来作为班级代号的 那可能学校里的学生们还是觉得入学年份更直观些？

**Comment by Yuchen-Wang-SH** [comment]
目前打算继续用入学年份来表示。主要是由于班级编号是由入学年份决定的原因，同学看起来直观一些
