### ISSUE TITLE
考研：文件模板

### ISSUE THREAD

**Issue by Yuchen-Wang-SH** [ECUST-Leap/ecust-leap.github.io#17]

**Comment by paulzrq** [comment]
---
tags:
  - <考研>
  - <本科学院>
  - <本科专业>
  - <本科入学年份>
  - <研究生学校，尽量写官方名称>
  - <研究生专业>
  - <以及其他任意觉得可以当tag的特征>
description: <一句话总结你的飞跃>
---

# nickname (2019) : program \@ school

## 基本背景

-   Major：xxxx

-   ubmajor：xxx

-   Grade： GPA xxx/4.00, Ranking: xx/xx

-   Certificate：

-   Skill：

## 科研经历

-   xx校内科研 xx暑研

-   xxx发表

## 实习经历

-   一段三中一华ibd，一段mbb

## 竞赛经历

- xxx

## 创业经历

- xxx

## 考研心得

### 数学

- xxx

### 英语

- xxx

### 政治

- xxx

### 专业课

- xxx

### 心态调整

- xxx

## 致谢

- xxx

- 如有问题欢迎联系（if possible）[xxx\@xxx.edu](mailto:xxx@xxx.edu){.email}
