### ISSUE TITLE
某种向读者推送更新的机制

### ISSUE THREAD

**Issue by Yuchen-Wang-SH** [ECUST-Leap/ecust-leap.github.io#200]
微信bot？

**Comment by pvvq** [comment]
RSS可以有一个，虽然不太有人会看

**Comment by pvvq** [comment]
> RSS可以有一个，虽然不太有人会看

文档：[https://docusaurus.io/docs/blog#feed](https://docusaurus.io/docs/blog#feed)
如果我能搞懂这段js的话我再提一个pr

**Comment by Yuchen-Wang-SH** [comment]
> By default, RSS and Atom feeds are generated.

不过RSS就连我自己也是最近才开始玩，我觉得很难让读者去了解RSS是什么并且下载对应的软件去看。

**Comment by pvvq** [comment]
哦哦我看漏了
这也确实

**Comment by Yuchen-Wang-SH** [comment]
我昨天研究了一下关于微信公众号推送，主要看了这个：https://github.com/wangxinleo/wechat-public-account-push

这里面提示的pushplus，server酱，都是需要用户去订阅这两个服务的公众号，然后我们再向这个服务发布消息，公众号就会推送出去。我个人觉得不美观不优雅（奇怪的审美），而且pushplus我记得free tier的话每个post会有广告，人多少还是得赚点钱。Wxpusher原理也一样。读者关注这些公众号的话，多少会收到点和我们没关系的来自服务本身的推送。

**Comment by Yuchen-Wang-SH** [comment]
微信测试号有限制：测试号的标题不能修改为自定义的名称，不能修改测试号的头像，推送的消息必须要点进订阅号才能收到，每次要修改内容必须要自定义模版。注册一个正经的微信公众号需要身份证信息，我有点膈应，而且不确定有没有我想要的REST API发布消息的功能

**Comment by Yuchen-Wang-SH** [comment]
目前我的想法是：基于GitHub Releases。想要接受推送的同学可以在repo上方的Watch -> Custom -> 勾选Releases。那每次publish release之后他们就应该能收到邮件。我要试验一下

concern是国内email的使用率不高，然后非EECS专业的同学也不太会使用GitHub。但是本网站在有GitHub和常用邮箱之后使用体验会好很多。

**Comment by Yuchen-Wang-SH** [comment]
微信公众号的话，以后有机会可以让学校这种组织创建一个

**Comment by Yuchen-Wang-SH** [comment]
推出了基于Release和email的推送方式。先暂时close了，以后有机会能让学校弄个公众号出来的话再看看微信行不行

#221 #223 #228 etc.

Related: #37
