### ISSUE TITLE
两篇文案：面向低年级邀请阅读 + 邀请高年级/校友征稿

### ISSUE THREAD

**Issue by Yuchen-Wang-SH** [ECUST-Leap/ecust-leap.github.io#219]

**Comment by paulzrq** [comment]
飞跃手册征稿

Hi 华理的朋友们，我们正在策划一件很酷的事情。我们决定重启华东理工大学的飞跃手册并将其命名为华理飞跃。

我们想为华理在校生解决一些疑问，比如：实习去哪儿找，托福怎么考，亦或是保研、考研选哪所学校。因此我们想邀请已经大四或者是已经毕业的校友们分享你们的答案，因为你们当时也一定被这些问题困扰着。

除了解决疑问，还有打破信息壁垒。我们在职业发展的道路上不断寻找着对自身有用的信息，伴随着迷茫与焦虑， 多少次感叹着若是有前人的经验该多好。

淋过雨的人才知道为别人撑伞，在此，我们诚邀华东理工大学大四或者是已经毕业的校友们分享你们的成功经验，形式大概就是一份小小的申请总结和回顾。

如果你愿意加入我们，分享你在 申请出国，保研，考研和求职方面的成功经验，欢迎参考https://ecust-leap.github.io/ 提供的投稿指南，如果困难，请联系目前维护者，如果你有意向与我们通行，欢迎联系ecust_leap@163.com

不限去向，不限专业，我们相信每一位朋友的成功经验都能帮助到更多的朋友！

**Comment by Yuchen-Wang-SH** [comment]
> 重启华东理工大学的飞跃手册并将其命名为华理飞跃

这个我不太确定，我本来觉得这只是个缩写而已。我甚至会想，如果以后有播客的话，那可能就叫华理飞跃播客，那播客和手册就都是华理飞跃的子品牌

**Comment by paulzrq** [comment]
飞跃手册宣传

Hi 学弟学妹们，开学快乐。我是Paul, 2022年毕业于华东理工大学数学学院，现就读于耶鲁大学生物统计专业（我不确定这半句要不要加）。

我给你们准备了一份开学礼物——飞跃手册。

如果你也像我一样，准备出国但在大二连托福考试考什么都不知道，你能在手册里找到最高效便捷的备考攻略

如果你也像我一样，大一结束还搞不清楚GPA的评判标准，你能在手册里发现前辈总结的提分绝学。

如果你也像我一样，想联系优秀的学长学姐缺却无从下手，你能在手册里和他们直接沟通交流。

在升学路上，我数次碰壁，资源匮乏，心态焦虑，看到其他高校的飞跃手册不禁羡慕。在毕业后，我不希望我的遗憾成为你的遗憾，于是就有了这份礼物。

希望你们能在其中获取所需的一切信息，将它分享给你的同学，朋友，并在毕业后分享自己的成功经验回馈你的后辈，如果你有意向与我们同行或者是有任何建议，欢迎联系[ecust_leap@163.com](mailto:ecust_leap@163.com)

祝你的飞跃一切顺利，加油。

**Comment by Yuchen-Wang-SH** [comment]
- 这个没放网址
- 我建议开头第一句的主语是我们整个团队？因为我们可能每个人都会去发的

**Comment by paulzrq** [comment]
我是觉得可以每个人后面写自己当时遇到的困惑，这样会不会好一点，显得真实。我是罗列了自己的，所以一直用的是“我”

**Comment by Yuchen-Wang-SH** [comment]
那这样会不会每个人要对这段话的改动太大了点 可能有好几段话要改掉

**Comment by Yuchen-Wang-SH** [comment]
我是想如果想自我介绍的话 可以在群里发完这句宣传语以后再自己发自己想说的

**Comment by paulzrq** [comment]
ok 那我明天改一下看看

**Comment by paulzrq** [comment]
飞跃手册宣传

Hi 学弟学妹，开学快乐。我们是华理飞跃team(我觉得要加一句表明身份的话，暂定这个。)

我们给你准备了一份开学礼物——飞跃手册https://ecust-leap.github.io/

如果你曾同我们一样，准备出国但在大二连托福考试考什么都不知道，你能在手册里找到最高效便捷的备考攻略

如果你曾同我们一样，大一结束还搞不清楚GPA的评判标准，你能在手册里发现前辈总结的提分绝学。

如果你曾同我们一样，想联系优秀的学长学姐却无从下手，你能在手册里和他们直接沟通交流。

如果你曾同我们一样，憧憬保研但对政策感到茫然无助，你能在手册里获取清北复交的独门秘籍。

如果你曾同我们一样，孤独而坚定地在考研路上前行，你能手册里汲取继续坚持的动力。


在升学路上，我们曾因资源匮乏、心态焦虑而到处碰壁，也曾因此对其他高校的飞跃手册羡慕不已。在毕业后，我们不希望过去遗憾在你们身上重演，于是便有了这份礼物。

希望你能在其中收获所需的信息，将它分享给周围同样需要它的同学、朋友，同样，我们也欢迎优秀的你在毕业后分享自己的成功经验回馈后辈。如果你有意向与我们同行或者是有任何建议，欢迎联系[ecust_leap@163.com](mailto:ecust_leap@163.com)

祝你的飞跃一切顺利，加油。

**Comment by Yuchen-Wang-SH** [comment]
looks good
