### ISSUE TITLE
找一个logo

### ISSUE THREAD

**Issue by Yuchen-Wang-SH** [ECUST-Leap/ecust-leap.github.io#30]
总不能是这个小恐龙吧

<img width="122" alt="image" src="https://user-images.githubusercontent.com/17931662/215295781-50d92222-d68d-4625-9f95-f188f266b0e1.png">

**Comment by Muro967** [comment]
如果做纯文字的如何，因为学生制作是不允许用校徽的，belike下面这种，但是这种很丑是真的hhh可以再设计一下

![Image](https://user-images.githubusercontent.com/103167971/215396840-727f6bb5-7295-46c6-8bea-fe1a6e7d181d.jpeg)

**Comment by Yuchen-Wang-SH** [comment]
`学生制作是不允许用校徽的`居然还有这个规定吗。不过我觉得自行设计一个也好，这种麻烦还是不要去趟比较好哈哈

**Comment by Muro967** [comment]
对的，我之前在小花梨，我们校徽和校名是有版权保护的，学生不能随便用

**Comment by Yuchen-Wang-SH** [comment]
有朋友提议用ai自动生成一个，比如 https://midjourney.com/home/

**Comment by Muro967** [comment]
啊哈 感觉是个不错的主意

**Comment by paulzrq** [comment]
才不用校徽，丢不起那人qwq
