### ISSUE TITLE
关于推广的时间线和措施

### ISSUE THREAD

**Issue by Yuchen-Wang-SH** [ECUST-Leap/ecust-leap.github.io#31]

**Comment by Yuchen-Wang-SH** [comment]
关于launch我刚有个很初步的想法，我的想法是分成两个阶段：
1. 第一个阶段，我们向我们认识的23年毕业的人征稿，那这样23年的人会是第一波看到我们网站的customer
2. 第二个阶段，收集到足够23年毕业的人的稿件以后，我们再面向所有更低年级的同学去宣传

之所以这样想是因为，如果我是一个大一大二大三的学生的话，我当然最关心的是最近的一届的人什么情况

我的criteria之一是 争取做到每个学院都至少有一篇稿子 甚至是每个学院的每种意向都有一篇稿子

目前保研优先于其他意向因为已经出完结果，其次是工作，考研以及出国

**Comment by Yuchen-Wang-SH** [comment]
@paulzrq `云村`帮忙推广？

**Comment by Yuchen-Wang-SH** [comment]
next step: @Ronten-Yang 需要一个doc来说一下下一步的推广该怎么做

**Comment by Ronten-Yang** [comment]
我现在的思考，估计官方途径的推广，当前阶段不现实。还是觉得依靠 学生群体中 的**_kol_**们，通过发挥他们的影响力，来传播我们的手册。而联系kol们主要可以通过 邀请（热情地、真诚地）为我们撰稿并转发。 这是我现在想到的措施

**Comment by Ronten-Yang** [comment]
至于云村的途径，我觉得可行，但是 我觉得需要现在评估一下云村在同学们眼中的形象，如果同学们觉得 云村平台 挺low的，那我们就不要与他们合作。

**Comment by Yuchen-Wang-SH** [comment]
Related: #270 #269 详见02/25/2023 meeting notes
