### ISSUE TITLE
首页文本修改

### ISSUE THREAD

**Issue by Yuchen-Wang-SH** [ECUST-Leap/ecust-leap.github.io#33]
https://ecust-leap.github.io/ 首页上的内容可能可以进行一些修改。也许可以在 #32 之后

1. 介绍华理飞跃手册是什么
2. 介绍使用方法，即包括了什么内容（故事和公告），信息是怎么分级的，年份代表的是级还是届，搜索功能，tag功能，论坛功能，GitHub源码，等。
3. 介绍我们的团队

**Comment by Yuchen-Wang-SH** [comment]
Related: #232

**Comment by paulzrq** [comment]
looks good to me

**Comment by Ronten-Yang** [comment]
halo, 我来试试这个系统哈哈哈
有点子需要时间熟悉
